permalink: /:title/
highlighter: pygments
markdown: redcarpet
name: csaba.palfi.me
assets:
  cache: false
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"
      type: "post"
