name: csaba.palfi.me
title: Csaba Palfi
logo: /assets/images/csabapalfi@2x.jpg
markdown: redcarpet
permalink: /:title/
sass:
    style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
